services:

  rabbitmq:
    image: rabbitmq:4-management

    env_file:
      - ./service-request/.env

    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  service-request:
    container_name: service-request
    build:
      context: ./service-request
    env_file:
      - ./service-request/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"

  service-provision:
    container_name: service-provision      
    
    build:
      context: ./service-provision
    
    env_file:
      - ./service-provision/.env  

    depends_on:
      - rabbitmq

  service-notification:
    container_name: service-notification
    
    build:
      context: ./service-notification
    
    env_file:
      - ./service-notification/.env

    depends_on:
      rabbitmq:
        condition: service_healthy